server:
  port: 8080

spring:
  datasource:
    url:  jdbc:postgresql://postgres-service:5432/mydb
    username: root-user-123
    password: root-user-123@
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  application:
      name: HOTEL-SERVICE


management:
  endpoints:
    web:
      exposure:
        include: health , info , beans , *


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8080/eureka

okta:
  oauth2:
    issuer: https://dev-34423417.okta.com/oauth2/default
    audience: api://default
